name: Deploy Javadoc

on:
  push:
    branches: [ master ]
    paths: [ '**.java' ]

jobs:
  api-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build docs with Maven
        run: mvn javadoc:javadoc

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.2.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: target/site/apidocs
          clean: true
          target_folder: javadoc

